### ISSUE TITLE
Autosync with CrowdIn via Github Actions

### ISSUE THREAD

**Issue by dmytrokyrychuk** [Ludeon/RimWorld-Ukrainian#34]
The current setup requires someone to manually build the project on CrowdIn, download the translated files and commit them to this repository.

I propose that we create a Github Actions workflow triggered weekly that downloads and commits the CrowdIn project changes automatically. For this to work we need to add a CrowdIn API token to this repo's settings.

**Comment by MartianDill** [comment]
Тут виявилось що мої виправлення для [LanguageInfo.xml](https://github.com/Ludeon/RimWorld-Ukrainian/blob/master/Core/LanguageInfo.xml) перезаписались старими даними при одній з таких ручних синхронізацій.
Тому треба спершу вивантажити все з Crowdin сюди, 
навести лад в гілці master (деякі файли мають бути всередині папки Core), 
повернути виправлену версію [LanguageInfo.xml](https://github.com/Ludeon/RimWorld-Ukrainian/blob/master/Core/LanguageInfo.xml)
оновити прапор, хоч він, схоже, вже ніде не відображується. Про це в [чаті](https://t.me/+Tposfrg1AwU5N2I6) колись [говорили](https://t.me/c/1757267493/1689)
вивантажити це все назад на Crowdin, щоб там була актуальна версія цих виправлених файлів

**Comment by dmytrokyrychuk** [comment]
Еталон файлів знаходиться на CrowdIn, а у цьому репозиторії зберігаються копії файлів звідти. При переносі файлів з CrowdIn сюди зміни дійсно втрачаються. Я вважаю, що такий односторонній метод синхронізації виконувати простіше. Бо при двосторонній синхронізації можуть виникати конфлікти, коли один файл було змінено і тут і на CrowdIn. Вирішення таких конфліктів вимагатиме людського втручання.

**Comment by dmytrokyrychuk** [comment]
I contacted Ludeon support over email with a request to add configuration variables for Github Actions, which they did not agree to do.

I am closing this issue since this is impossible to implement without cooperation from the repository owners.
